# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d%H%M')"
      - name: Change Folder into Athena_Engine
        run: cd Athena_Engine
      - name: Build Athena_Engine
        run: dotnet build --configuration Release /p:Version=${{ steps.date.outputs.date }}
      - name: Package Athena_Engine
        run: dotnet pack --configuration Release /p:Version=${{ steps.date.outputs.date }} --no-build --output .
      - name: Send it to nuget
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN}}
      

